# Fyrirlestur 3

Dagsetning: 28. febrúar

Python uppsetning

In [5]:
import numpy as np
import math

Helsta efni:
 - fara yfir sýðustu verkefin 
 - fara yfir heima dæmi
 - smá python kyning

# Heimadæmi
1\. Til að sýna að fall $f(x)$ sé línulegt er nóg að sýna vigur $a$ sem er þannig að $f(x)=a^Tx$. 

a) Sýnið að meðaltal staka í sætum með slétt sætisnúmer í $n$-vigri sé línulegt fall. Þið megið gera ráð fyrir að $n$ sé slétt tala, $n=2k$. *Dæmi*: $f((1,2,3,4))= 2/2 + 4/2 = 3$. 

**Lausn**: Set $a_i=0$ fyrir oddatölu $i$ en $a_i=2/n$ fyrir slétt $i$, $i=1,\ldots,n$.

b) Sýnið að eftirfarandi "brúun" á $n$-vigri sé línulegt fall, $x_n + (x_n - x_{n-1})$ fyrir $n \geq 2$ (þetta er einföld aðferð til að spá fyrir um gildi á $x_{n+1}$ sem byggir á að teikna línu gegnum $x_n$ og $x_{n-1}$).

**Lausn**: $a$ er $n$-vigur með stökum $a=(0,...,0,-1,2)$.


2\. Til að sýna að fall sé ólínulegt er nóg að finna tiltekna vigra $x$ og $y$ og tölur $\alpha$ og $\beta$ þannig að
$
  f(\alpha x + \beta y) \neq \alpha f(x) + \beta f(y).
$

a) Sýnið að $f(x)=(x_1-x_2+x_3)^2$ sé ólínulegt fall.

**Lausn**: $x=(1,1,1), y=(-1,-1,-1), \alpha=\beta=1$. Þá er $f(\alpha x + \beta y)= f( (0,0,0) ) = 0$ en $\alpha f(x) + \beta f(y) = (1-1+1)^2 + (-1+1-1)^2 = 1 + 1 = 2$ þ.a. $f(x)$ er ólínulegt.

b) Sýnið að miðgildi $n$-vigurs sé ólínulegt fall. Gerið ráð fyrir að $n$ sé oddatala, þ.e. $n=2k+1$. Miðgildi vigurs er skilgreint sem $(k+1)$-stærsta stakið. *Dæmi*: Miðgildi vigursins (-1.2, 1, 3, 0.5, -2) er 0.5.

**Lausn**: Vel $x=(1,3,2)$, $y=(2,-3,3)$ og $\alpha=\beta=1$. Þá fæst
$f(\alpha x + \beta y)=f((1,3,2) + (2,-3,3))=f( (3,0,5)) = 3$ en $\alpha f(x) + \beta f(y)=(1)2+(1)2 = 4$ þ.a. fallið er ekki línulegt.

3.Skrifið Python föll sem reikna stærðirnar hér að neðan. Þið megið nota Numpy föllin `dot`, `ones`, `sum`, `sqrt` og öll svið í `ndarray`, t.d. `ndim` og `shape`. Föllin taka inn vigur $x$ eða vigra $x$ og $y$.

a) $||x||^2$

b) **std**$(x)$

c) $\rho = \frac{\tilde{x}^T \tilde{y}}{||\tilde{x}|| ||\tilde{y}||}$ (hér táknar $\tilde{x} - \textbf{avg}(x)$, sjá nánar bls. 60 í bók).


4\. Notið Python og Numpy til að finna *næsta nágranna* við $a=(1,3,4)$ meðal vigranna
$$
x_1=(4,3,5),\qquad x_2=(0.4,10,50),\qquad x_3=(1,4,10),\qquad x_4=(30,40,50).
$$
(Næsti nágranni $a$ meðal vigra $x_1,\ldots x_m$ er sá vigur $x_k$ sem er í stystri fjarlægð frá $a$).

Hver vigranna $x_1,\ldots,x_4$ er næsti nágranni $a$ og hver er fjarlægð $a$ í hann?
Hver vigranna $x_1,\ldots,x_4$ myndar minnsta horn við $a$? Tilgreinið líka þetta horn.

*Ábending*: Sjá vika_02.pynb á Piazza. Notið `math.acos` til að reikna arccos fallið (andhverfa kósínius fallsins).

In [6]:
# Lausn á heimadæmi 3
def avg(x):
    n=x.shape[0]
    return np.dot((1/n)*np.ones(n), x)
def sqnorm(x):
    return np.dot(x,x)
def std(x):
    n=x.shape[0]
    s = x - avg(x)*np.ones(n)
    return np.sqrt(np.dot(s,s)/n)
def cor(x,y):
    x = x - avg(x)
    y = y - avg(y)
    normx = np.sqrt(np.dot(x,x))
    normy = np.sqrt(np.dot(y,y))
    return np.dot(x,y)/(normx*normy)

In [7]:
# Lausn á heimadæmi 4

a=np.array([1,3,4])
X=np.array([[4,3,5],[0.4,10,50],[1,4,10],[30,40,50]])

n,m=X.shape
fjarl=np.zeros(n)
horn=np.zeros(n)
for i in range(n):
    fjarl[i]=np.linalg.norm(a - X[i,:])
    horn[i]=math.acos(np.dot(a,X[i,:])/(np.linalg.norm(a)*np.linalg.norm(X[i,:])))
print(fjarl)
print(horn)

j=np.argmin(fjarl) # Númer minnsta staks í 'fjarl'
k=np.argmin(horn)
print("Næsti nágranni a er ", X[j,:], "fjarlægðin er ", fjarl[j])
print("Vigur sem myndar minnsta horn er ", X[k,:], "hornið er ", horn[k])  


[ 3.16227766 46.53342884  6.08276253 65.77233461]
[0.41465511 0.48187704 0.28041747 0.24256387]
Næsti nágranni a er  [4. 3. 5.] fjarlægðin er  3.1622776601683795
Vigur sem myndar minnsta horn er  [30. 40. 50.] hornið er  0.24256387409548533


# Tímadæmi
 
1\. Dæmi 4.2 í bók.

**Lausn**:

a) [Teiknið mynd af nokkrum punktum sem mynda 2 hópa í pósitífa fjórðungi hnitakerfisins og sýnið miðpunktar hópanna lenda líka í pósitífa fjórðungnum]. Nánar:

Fulltrúi $z_j$ er meðaltal hlutmengis af vigrunum $x_1,\ldots,x_N$, $$z_j = \frac{1}{|G_j|} \sum_{i \in G_j} x_i$$ þar sem $G_j$ er mengi sem inniheldur vísa (e. indices) fyrir punktana sem eru í $z_j$ (sjá bls. 72 í bók). Meðaltal af ekki-neikvæðum stærðum verður alltaf ekki-neikvætt.

b) [Hér er gott að byrja á einföldu dæmi. G.r.f. að $G_1=\{1,2\}$ og $x_1=(0.3, 0.7)$ og $x_2=(0.1, 0.9)$ þá er $(z_1)_1=(0.3+0.1)/2=0.2$ og $(z_1)_2=(0.7+0.9)/2=0.8$ og þá $(z_1)_1 + (z_1)_2 = 0.2 + 0.8 = 1$] Nánar:
\begin{eqnarray*}
(z_j)_1 + \ldots (z_j)_n = \frac{1}{|G_j|} \sum_{i \in G_j} (x_i)_1 + \ldots + \frac{1}{|G_j|} \sum_{i \in G_j} (x_i)_n
			 &=& \frac{1}{|G_j|} \sum_{i \in G_j} ((x_i)_1 + \ldots + (x_i)_n)
			 &=& \frac{1}{|G_j|} \sum_{i \in G_j} (1)
			 &=& \frac{1}{|G_j|} (|G_j|)(1)
			 &=& 1.
\end{eqnarray*}

c) $i$-ta stak $j$-ta fulltrúa, $(z_j)_i$, má túlka sem hlutfall $x$-vigra í hópi $j$ sem hafa $i$-ta stak jafnt einum. Ef $x$ geymir t.d. upplýsingar um sjúklinga og $(x_\ell)_i$ er 1 ef sjúklingur $\ell$ hefur verk fyrir brjósti þá er $(z_j)_i$ hlutfall sjúklinga í hópi $j$ með brjóstverk.


2\. Dæmi 5.1 í bók.

**Lausn**:

a) Nei. Mótdæmi eru vigrar $a_1,\ldots a_k$ og $b_1,\ldots,b_k$ með $k > n+m$ sbr. setningu í grein 5.2 sem segir að línulega óháð safn af  $n$-vigrum getur mest haft  $n$--stök. Með öðrum orðum, sérhvert safn  $n+1$ eða fleiri $n$-vigra er línulega háð.

b) Nei. Motdæmi er t.d. $a_1=(1,0),~a_2=(2,0)$ og $b_1=(0),~ b_2=(1)$. Vigrarnir $a_1$ og $a_2$ eru línulega háðir en blokkvigrarnir $c_1$ og $c_2$ eru línulega óháðir.


3\. Dæmi 5.6 í bók.

**Lausn**:
Þar sem $||a_1||=1$ er $q_1=a_1$.
Vigurinn $q_2 = a_2 - (q_1^T a_2) q_1 = (1,1,0,\ldots,0) - ((1,0,\ldots,0)^T(1,1,0,\ldots,0))(1,0,\ldots, 0) 
	      = (1,1,0,\ldots,0) - 1(1,0,\ldots,0) = (0,1,0,\ldots,0)$.
Á sama hátt fæst að $q_3 = (0,0,1,0,\ldots,0)$ og almennt að $q_i=e_i$ (þar sem $e_i$ táknar $i$-ta einingavigur). Reikniritið keyrir þannig til enda og $a_1,\ldots,a_k$ því grunnur.

# Sýnidæmi

Fylki eru af taginu `ndarray` alveg eins og vigrar

In [3]:
A = np.array([[0,1,-2,0.2], [1.4,0,-1,10],[3.1, -1,4,5]]) # listi af listum
print(A)
print(type(A))
print('A.size = ', A.size) # fjöldi staka í fylkinu
print('A.ndim = ',A.ndim) # fjöldi vídda, 2 fyrir fylki
print('A.shape = ',A.shape) # fjöldi raða, fjöldi dálka

[[  0.    1.   -2.    0.2]
 [  1.4   0.   -1.   10. ]
 [  3.1  -1.    4.    5. ]]
<class 'numpy.ndarray'>
A.size =  12
A.ndim =  2
A.shape =  (3, 4)


Tilvísun í stök virkar eins og fyrir vigra, byrjum að telja í 0

In [4]:
print(A[1][0]) # getum notað A[0][0] eins og í java
print(A[1,0])  # getum líka vísað í stök með kommum á milli (tuple)
v = (1,0)
print(A[v])

1.4
1.4
1.4


## Tilvísanir í dálka og raðir

In [5]:
print(A[0]) # A[0] gefur fyrstu röð, línuvigur
u = A[0]
print(u.shape)
print(u.ndim) # u er hérna n-vigur, en við gerum greinarmun í stærðfræði

[ 0.   1.  -2.   0.2]
(4,)
1


In [6]:
print(A[:,0]) # A[:,0] gefur fyrsta dálk
v = A[:,0]
print(v.shape)
print(v.ndim) # v er venjulegur vigur

[ 0.   1.4  3.1]
(3,)
1


## Hlutfylki/blokkir

In [7]:
print(A[0:2,0:2]) # fyrstu tveir dálkar og tvær raðir

[[ 0.   1. ]
 [ 1.4  0. ]]


## Fylki úr dálkum
Ef við höfum lista af vigrum þá getum við búið til fylki úr þeim með `column_stack` fallinu sem dálka, eða `vstack` með röðum

In [8]:
v1 = np.zeros(5)
v2 = np.ones(5)
B = np.column_stack([v1,v2,v1])
print('B = ',B)
C = np.vstack([v1,v2,v1])
print('C = ',C)

B =  [[ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]]
C =  [[ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.]]


## Sérstök fylki

Núllfylkið og einingafylkið fást með föllunum `zeros` og `eye` (borið fram "æ")

In [9]:
Z = np.zeros((3,4)) # (3,4) þarf að vera í tuple, np.zeros(3,4) virkar ekki
print('Z = ',Z)
I = np.eye(5) # I er ferningslaga
print(I)

Z =  [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


Hornalínufylki fást með `diag` fallinu

In [10]:
C = np.diag([1,2,3]) # listi af tölum
print(C)
C = np.diag(np.random.random(5)) # eða numpy vigur
print(C)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[ 0.97678335  0.          0.          0.          0.        ]
 [ 0.          0.967279    0.          0.          0.        ]
 [ 0.          0.          0.37918655  0.          0.        ]
 [ 0.          0.          0.          0.60356313  0.        ]
 [ 0.          0.          0.          0.          0.87978343]]


## Bylt fylki

fæst með `transpose` fallinu

In [12]:
print('A = \n',A)
AT = np.transpose(A) # líka hægt að nota A.T
print('A^T = \n',AT)

A = 
 [[  0.    1.   -2.    0.2]
 [  1.4   0.   -1.   10. ]
 [  3.1  -1.    4.    5. ]]
A^T = 
 [[  0.    1.4   3.1]
 [  1.    0.   -1. ]
 [ -2.   -1.    4. ]
 [  0.2  10.    5. ]]


## Samlagning og margföldun

Við notum venjulega virkja, `+` og `*`

In [13]:
B = np.array([[0,2,1,5],[1,0,-4,2],[1,5,2,0.0]])
print('A+B = ',A+B)
print('3*A = ',3*A)
#A + np.transpose(B) ## skilar villu, stærðirnar passa ekki

A+B =  [[  0.    3.   -1.    5.2]
 [  2.4   0.   -5.   12. ]
 [  4.1   4.    6.    5. ]]
3*A =  [[  0.    3.   -6.    0.6]
 [  4.2   0.   -3.   30. ]
 [  9.3  -3.   12.   15. ]]
