# Dæmatími 2

## Helstu atriði

- Fara yfir dæmi fyrri viku
- Fara yfir lausnir á tíma dæmum

Hlekkir til að skoða
https://docs.python.org/3/

1\.  Lát $a = (1, 2, 3, 4, 6)$ og $b = (6, 7, 8, 9, 10)$. Táknið eftirfarandi aðgerðir með aðgerðum í numpy. Athugið að hvert svar á að vera einungis ein lína af Python kóða. Ef einhver aðgerð er ekki vel skilgreind í línulegri algebru þá merkið þið það svar sérstaklega og skilið ekki Python kóða.

1. $a+2b$


In [9]:
import numpy as np
a = np.array([1,2,3,4,6])
b = np.array([6,7,8,9,10])

print(a+2*b)

[13 16 19 22 26]


$\left[ \begin{array}{c} a \\ b \end{array} \right]$

In [11]:
np.hstack([a,b])

array([ 1,  2,  3,  4,  6,  6,  7,  8,  9, 10])

$ a+ 1_4$
#### ekki vel skilgreint í stærðfræði

$ 2 + b$
#### ekki vel skilgreint í stærðfræði

$a_1 + b_2 - a^T b$

In [12]:
print(a[0] + b[1] - np.dot(a,b))

-132


2\. Dæmi 1.6 í bók. *Viðbót*: Gefið einnar línu Python kóða sem notar numpy aðgerð(ir) til að reikna mismunavigurinn fyrir $x=(0,2,-1,4,6)$.

In [13]:
# 2. (Dæmi 1.6)
x=np.array([0,2,-1,4,6])
n=len(x)
d=x[1:n] - x[0:n-1]
print(d)


[ 2 -3  5  2]


3\. Dæmi 1.10 í bók.

In [16]:
# 3. (Dæmi 1.10)
#r=[h1,h2,h3,h4,h5,h6,h7,h8,midterm,final]
#w=[0.25*100/10/8, ..., 0.25*100/10/8, 0.35*100/120, 0.40*100/160]
w=[0.3125, ..., 0.3125, 0.2917, 0.2500]


4\. Í þessu dæmi átt þú að mæla hversu langan tíma tölvan þín er að reikna innfeldi tveggja vigra af lengd $10^8$ (100 milljón) og ákvarða (mjög gróflega) í framhaldinu hversu marga milljarða fleytitöluaðgerðir tölvan getur framkvæmt á sekúndu (Gflops/sec).

Notið `numpy.random.random` fallið í til að búa til tvo slembivigra af lengd $10^8$ (stökin í vigrunum eru tölur sem eru valdar af handahófi á bilinu 0 til 1), reiknið innfeldi vigranna með numpy og mælið tímann sem það tekur. Hversu mörg Gflops/sec getur tölvan þín framkvæmt? Hversu langan tíma tæki að reikna innfeldið í "höndunum" ef gert er ráð fyrir að maður geti framkvæmt eina fleytitöluaðerð á 10 sekúndna fresti, 8 klst á dag, alla daga ársins?

`%time` galdraskipunin er notuð til að mæla tíma. Sjá nánar http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-time

Til að fá nákvæmara tímamat getur þurft að keyra nokkrum sinnum (fyrsta keyrsla tekur líklega lengsta tímann). Til að fá meðaltíma úr nokkrum keyrslum getið þið notað `%timeit` galdraskipunina.

*Athugasemd*: Ef tölvan ræður ekki við vigra af lengd $10^8$ þá þurfið þið að nota vigra með færri stökum, t.d. $10^7$.

In [19]:
n=10**8
a=np.random.random(n)
b=np.random.random(n)

%time s=a.dot(b)
# Fjöldi fleytitöluaðgerða í innfeldi tveggja n staka vigra er n margfeldi og n-1 samlagningar, þ.e. 2n-1 aðgerðir
# Fjöldi fleytitöluaðgerða/sek er þá (2n-1)/t þar sem t er tíminn sem keyrslan hér að ofan tók (í sek) og n=10**8.
# Tölvan mín er 73ms að framkvæma innfeldið og það svarar til 2.7 Gflops/s
#
# Maður sem getur framkvæmt 360 aðgerðir á klst, þ.e. 2880 aðgerðir á dag yrði 2*10**8/2880=69444 daga
# að framkvæma útreikningana en það svarar til 190 ára.

Wall time: 96.7 ms


5\. Fyrir sérhvern lið hér að neðan eigið þið að skrifa stutt Python forrit sem útbýr vigurinn $a$ sem um er beðið. Notið `numpy.array` til að geyma $a$. Sannreynið að $a^T x$ gefi rétt svar með því að nota slembivigur $x$ (notið `numpy.random.random` fallið).

1. $a^T x$ "velur" (er jafnt og) 5. stak í 10-vigrinum $x$.
2. $a^T x$ er vegið meðaltal 3-vigurs $x$ þar sem fyrsta stakið hefur vægi 0.3, annað stakið vægi 0.4 og þriðja stakið vægi 0.3.
3. $a^T x$ er meðaltal þeirra 5 staka sem eru í miðjum 11-vigrinum $x$.


In [18]:
# 5.
# i)
n=10
x=np.random.random(n)
a=np.zeros(n)
a[4]=1
print(x)
print("Fimmta stak er ", x[4])
print(a.dot(x))

# ii)
n=3
x=np.random.random(n)
a=np.array([0.3, 0.4, 0.3])
print(x)
print("Vegið meðaltal x er ", a.dot(x))

# iii)
n=11
x=np.random.random(11)
a=np.zeros(11)
a[4:8]=1/5
print(x)
print("Meðaltal 5 staka í miðjum vigri er ", a.dot(x))

[ 0.06212425  0.10622288  0.40395059  0.11464374  0.24924235  0.31723745
  0.65335475  0.9216703   0.93151158  0.5554826 ]
Fimmta stak er  0.249242351808
0.249242351808
[ 0.95627955  0.87082439  0.95384748]
Vegið meðaltal x er  0.921367863615
[ 0.24313695  0.22431085  0.74650109  0.15805742  0.11148029  0.31077239
  0.1305293   0.30028403  0.7239665   0.47525428  0.69836129]
Meðaltal 5 staka í miðjum vigri er  0.17061320028


# Tíma Dæmi 2


1\. Til að sýna að falll f(x) er línulegt er nóg að sýna vigur a sem er þannig að f(x) = $a^T x$ . sýnið að mismunur fyrsta og síðasta staks í n-vigri sé línulegt fall f(x) = $x_n - x_1$

**Lausn**: Læt $a_i=0$ fyrir $i=2,\ldots,n-1$ og $a_1=-1$ og $a_n=1$.

2\. til að sýna að fall sé ólínulegt er nóg að finna tiltekna $x $ og $y $ vigra og tölur $alpha $ $beta $ þannig að $f(\alpha x + \beta y) \neq  \alpha f(x) + \beta f(y) $

sýnið að fallið $f(x) = max_k x_k - min_k x_k $

Dæmi: $ f((4, 3, 1, 2)) = 4 - 1 = 3 $

**Lausn**: Með $x=(-1,1), y=(1,-1)$ og $a=b=1$ fæst $\max\{x_1,x_2\}=1, min\{x_1,x_2\}=-1, max\{y_1,y_2\}=1$ og $\min\{y_1,y_2\}=-1$.
Þá er $f(\alpha x + \beta y) = f( (-1,1)+(1,-1) ) = f( (0,0) ) = 0 - 0 = 0$ en
$\alpha f(x) + \beta f(y) = (1 - (-1)) + (1 - (-1)) = 2 + 2 = 4$. Fallið $f(x)$ er því ekki línulegt.


3\. Skrifið Pyhon fall sem reiknar stærðina $ x - avg(x)$. Þið megið nota Numpy föllin dot, ones, sum, sqrt og öll svið í ndarray, t.d. ndim og shape. fallið tekur viguri $ x $ af taginu numpy.ndarray

In [21]:
def demean(x):
    n=x.shape[0]
    avg = np.dot((1/n)*np.ones(n), x)
    x = x - avg
    return x